log_level = "DEBUG"
log_dir = "/home/yuehl/projects/Other/personal/websiteWatcher/logs"

[project]
author = "Yu-Yueh Liu"
version = "0.0.1"
description = "WebsiteWatcher is a Python CLI tool for running a website watcher"
list_watcher = "List Watcher monitors changes in a list of items"
price_watcher = "Price Watcher monitors changes in the price of an item"

[watcher_settings]
polling_interval = 10

[email]
api_key = "some_api_key"
sender = "from_email@example.com"
recipient = "to@example.com"
