log_level = "DEBUG"
log_dir = "/home/yuehl/projects/Other/personal/websiteWatcher/logs"

[project]
author = "Yu-Yueh Liu"
version = "1.0.0"

[watcher_settings]
polling_interval = 10

[email]
api_key = "some_api_key"
sender = "from_email@example.com"
recipient = "to@example.com"
